---
kind: pipeline
type: docker
name: build

volumes:
  - name: bundle
    host:
      path: /home/data/drone/gems
  - name: rubygems
    host:
      path: /home/data/drone/rubygems

spec_step_common: &spec_step_common
  pull: if-not-exists
  volumes:
  - name: bundle
    path: /bundle

steps:
- name: build on ruby2.4
  image: abakpress/ruby-app:2.4-latest
  environment:
    TEST_DB_HOST: postgres
    TEST_DB_NAME: docker
    TEST_DB_USERNAME: postgres
    BUNDLE_PATH: /bundle/2.4
  commands:
  - bundle install
  - bundle exec appraisal install
  - bundle exec appraisal bundle exec rspec
  <<: *spec_step_common

- name: build on ruby2.7
  image: abakpress/ruby-app:2.7-latest
  environment:
    TEST_DB_HOST: postgres
    TEST_DB_NAME: docker
    TEST_DB_USERNAME: postgres
    BUNDLE_PATH: /bundle/2.7
  commands:
  - cp gemfiles-27/Gemfile.lock Gemfile.lock
  - cp gemfiles-27/*.gemfile.* gemfiles/
  - bundle install
  - bundle exec appraisal install
  - bundle exec appraisal bundle exec rspec
  <<: *spec_step_common

- name: release
  image: abakpress/gem-publication:latest
  pull: if-not-exists
  when:
    event: push
    branch: master
    status: success
  volumes:
  - name: rubygems
    path: /root/.gem
  commands:
    - release-gem --public
